### ISSUE TITLE
Enable dark-mode support by default

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1430]
In next major version let's move dark-mode support out from behind the `skin-experiment-dark-mode` "flag" so that it becomes switched on by default.

```css
@media (prefers-color-scheme: dark) {
    .skin-experiment-dark-mode {
        .page-notice {
            --page-notice-color: @color-text-default-dark-mode;
            --page-notice-general-background-color: @color-grey1-dark-mode;
            ...
        }
    }
}
```

Would become:

```css
@media (prefers-color-scheme: dark) {
    .page-notice {
        --page-notice-color: @color-text-default-dark-mode;
        --page-notice-general-background-color: @color-grey1-dark-mode;
        ...
    }
}
```
