### ISSUE TITLE
Checkbox & Radio: Use SVG data-uri as background-image

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#20]
As suggested by Pranav, inline SVG seems a little too cumbersome for the case of default checkbox (and radio), let's see if we can leverage SVG data-uri to make things a little easier.

Current markup:

```html
<span class="checkbox">
    <input class="checkbox__control" type="checkbox" />
    <span class="checkbox__icon" hidden>
        <svg aria-hidden="true" focusable="false">
            <use xlink:href="#svg-icon-checkbox"></use>
        </svg>
    </span>
</span>
```

Potential/proposed:

```html
<span class="checkbox">
    <input class="checkbox__control" type="checkbox" />
    <span class="checkbox__icon" />
</span>
```

If background image works well, the old markup would continue to be supported for backwards compatibility and the additional flexibility that inline SVG affords.

This issue also applies to radio button.

**Comment by ianmcburnie** [comment]
Seems to work well. Will schedule this into v3.1.0 release. The only slightly funky thing is that I have to use the `:not([hidden])` selector in order to use the same `.checkbox__icon` name. To avoid this, we *could* use a different name, but can discuss more at PR time.

Huge shoutout to Pranav Jha (@pranavjha) as the inspiration behind this improvement!!

```css
.checkbox__icon:not([hidden]) {
    background:url(data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A//www.w3.org/2000/svg%27%20width%3D%2732%27%20height%3D%2732%27%3E%3Cpath%20%20fill%3D%22%23cccccc%22%20d%3D%22M25.107%2032.030h-18.214c-3.456%200-6.268-2.81-6.268-6.264v-19.529c0-3.456%202.812-6.268%206.268-6.268h18.214c3.456%200%206.268%202.812%206.268%206.268v19.529c0%203.452-2.812%206.264-6.268%206.264zM6.893%201.85c-2.419%200-4.386%201.967-4.386%204.386v19.529c0%202.417%201.967%204.382%204.386%204.382h18.214c2.419%200%204.386-1.965%204.386-4.382v-19.529c0-2.419-1.967-4.386-4.386-4.386h-18.214z%22%3E%3C/path%3E%3C/svg%3E);
    background-size: contain;
    width: 1em;
    height: 1em;
}

.checkbox__control[type="checkbox"] {
    &:checked + .checkbox__icon:not([hidden]) {
        .mixin-bounce-animation;
        background-image: url(data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A//www.w3.org/2000/svg%27%20width%3D%2732%27%20height%3D%2732%27%3E%3Cpath%20fill%3D%22%230654ba%22%20d%3D%22M0.543%205.647c0-3.119%202.531-5.647%205.65-5.647h19.309c3.12%200%205.65%202.511%205.65%205.647v20.705c0%203.119-2.531%205.647-5.65%205.647h-19.309c-3.12%200-5.65-2.511-5.65-5.647v-20.705zM5.313%2017.587l7.039%206.839%2013.831-13.439-2.636-2.561-10.929%2010.62-4.442-4.317-2.862%202.858z%22%3E%3C/path%3E%3C/svg%3E);
    }

    &:focus + .checkbox__icon:not([hidden]) {
        outline: @outline-dotted;
    }

    &[disabled] + .checkbox__icon:not([hidden]) {
        .opacity(0.5);
    }
}
```

![screen shot 2017-09-06 at 2 53 33 pm](https://user-images.githubusercontent.com/38065/30136320-4a8b2d2c-9313-11e7-9671-335ce8c8b542.png)
