### ISSUE TITLE
icons: tweak disabled modifier to support colored icons

### ISSUE THREAD

**Issue by ArtBlue** [eBay/skin#2231]
### Description

Skin currently has a disabled modifier for icons (`icon--disabled`) that makes icons look disabled by applying:

```css
svg.icon--disabled {
  color: var(--color-foreground-disabled);
  fill: currentColor;
}
```

Since colored icons are "fixed" assets and don't get dynamic coloring, the current disabled modifier doesn't work on them. 

To support disabled colored icons, minor adjustments are needed to the modifier, specifically, something along this to treat colored icons slightly differently:

```css
svg.icon--disabled[class~="-colored"] {
  filter: grayscale(100%);
  opacity: 85%; 
}
```

Grayscale is a must while opacity and/or any other types of filters will need to be determined by/with DS.

### Screenshots

<img width="636" alt="image" src="https://github.com/eBay/skin/assets/1675667/f0cb8e58-d489-43ea-8384-e8789c5e8ae4">

### Engineering pre-requisites

- [x] Successful design review with Design System Team.
- [x] Supports dark mode.
- [x] Supports responsive design.
- [x] Tokens have been provided (or already exist).
- [ ] Successful accessibility review with Core A11Y Team.
- [x] Successful frontend review with eBayUI Team.
