### ISSUE TITLE
Color: retrofit to DS4

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#228]
In DS4 the colours were only available via LESS variables. This module makes them available as classes, which is useful for static sites with no preprocessor.

**Comment by ianmcburnie** [comment]
Can potentially wait till after v6. Doesn't seem urgent for coreui.

**Comment by seangates** [comment]
Sure. That way DS4 and DS6 have the same functionality, which we may need to have around for a while.

**Comment by ianmcburnie** [comment]
I was hoping we could make the classes match up with ds6. Basically mapping all these classes to ds4 variables as best we can:

```css
.color-text-default {
    color: @ds6-color-text-default;
}

.color-text-secondary {
    color: @ds6-color-text-secondary;
}

.color-link-default {
    color: @ds6-color-link-default;
}

.color-link-visited {
    color: @ds6-color-link-visited;
}

.color-information-background {
    background-color: @ds6-color-information-background;
}

.color-warning-background {
    background-color: @ds6-color-warning-background;
}

.color-confirmation-text {
    color: @ds6-color-confirmation-text;
}

.color-confirmation-background {
    background-color: @ds6-color-confirmation-background;
}

.color-critical-text {
    color: @ds6-color-critical-text;
}

.color-critical-background {
    background-color: @ds6-color-critical-background;
}
```
