### ISSUE TITLE
button: fake button disabled missing styles

### ISSUE THREAD

**Issue by ArtBlue** [eBay/skin#2387]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

The fake button doesn't look disabled.

### Expected behavior

The fake button should look disabled.

### Skin version

18.0.6

### Device/OS/Browser info

All

### Steps to reproduce

```bash
1.View a disabled fake button
...
```

### Relevant code block

Looks to be a `css` specificity issue.

To fix, we'd likely do this in button.

```css
a.fake-btn:not([href]), a.fake-btn[aria-disabled=true] {
    color: var(--link-forground-color-disabled, var(--color-foreground-disabled));
}
```
