### ISSUE TITLE
page-grid: content in grid layout is cut off when printing page

### ISSUE THREAD

**Issue by weibichen** [eBay/skin#2591]
#### How to reproduce:
1. Open https://www.ebay.com/help/buying/returns-items-not-received-refunds-buyers/get-help-item-hasnt-arrived?id=4042
2. In MacOS, press "command + p" to print screen
3. Content in `<div class="all_content">` is cut off because content is overflow in printer view.

#### Root cause:
The `screen` media query in below source code, which breaks grid layout in printer view
```css
@media screen and (min-width: 512px) {
    :root {
        --page-grid-number-cols: 16;
        --page-grid-column-gaps: var(--spacing-200);
        --page-grid-column-widths: calc(6.25% - var(--spacing-200) +1px);
        --page-grid-outside-margins: 32px;
    }
}
```

#### Issue:
<img width="1686" alt="Image" src="https://github.com/user-attachments/assets/e4366e13-9dd9-49a2-a5e7-65e2b286de00" />

##### Browser screen view:

<img width="2151" alt="Image" src="https://github.com/user-attachments/assets/ab7ed253-629d-4302-9209-06f4b1fd80a4" />

##### Printer view:

<img width="2152" alt="Image" src="https://github.com/user-attachments/assets/2c846e64-ce14-4ba0-a2ac-478a9e8b578a" />

### Engineering pre-requisites

- [ ] Supports dark mode.
- [ ] Supports responsive design.
- [ ] Tokens have been provided (or already exist).
