### ISSUE TITLE
Actionable: remove duplicate selectors and normalize variables (our path to native CSS variables!)

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#502]
So, currently (in 7.0.0 branch) the selectors for ds4 and ds6 are exactly the same. The only delta is the variable name. This means we have a code duplication issue.

ds4/actionable.less

```less
@import "../../less/ds4/variables.less";
@import "../../less/ds4/mixins.less";
@import "../base/actionable.less";

button.icon-btn,
a.icon-link {
    svg {
        color: @ds4-color-icon-actionable-default;
    }

    &:active svg {
        color: @ds4-color-icon-actionable-active;
    }
}

button.icon-btn--badged,
a.icon-link--badged {
    .badge {
        border-color: @ds4-color-core-white;
        font-size: @ds4-font-size-12;
    }
}

a.img-link {
    &[href] {
        &:hover,
        &:focus {
            border-color: @ds4-color-core-gray-spanish;
        }

        &:active {
            border-color: @ds4-color-core-gray-dim;
        }
    }
}
..snip..
```

ds6/actionable.less

```less
@import "../../less/ds6/variables.less";
@import "../../less/ds6/mixins.less";
@import "../base/actionable.less";

button.icon-btn,
a.icon-link {
    svg {
        color: @ds6-color-text-default;
    }

    &:active svg {
        color: @ds6-color-text-default;
    }
}

button.icon-btn--badged,
a.icon-link--badged {
    .badge {
        border-color: @ds6-color-badge-text;
        font-size: @ds6-font-size-12;
    }
}

a.img-link {
    &[href] {
        &:hover,
        &:focus {
            border-color: @ds6-color-grey3;
        }

        &:active {
            border-color: @ds6-color-text-secondary;
        }
    }
}
..snip..
```

We should try and flip this paradigm around so that there is no code duplication and instead just a single LESS file, with normalized variable names. `@ds4-color-icon-actionable-default` and `@ds6-color-text-default`can just become `@actionable-icon-color` for example. We would then need to pull in either `ds4/actionable-variables.less` or `ds6/actionable-variables.less` accordingly.

```less
@import "ds-variables.less"; // this is the magic part, pulling in the right file based on ds

button.icon-btn,
a.icon-link {
    svg {
        color: @actionable-icon-color;
    }

    &:active svg {
        color: @actionable-icon-color-active;
    }
}
..snip
```

If we do this for actionable, I'm sure there are other modules that would benefit from a similar refactoring.

This also gets us closer to using native CSS variables.

**Comment by seangates** [comment]
Are you intending this for only Actionable? Or, should we extend this to all components?

**Comment by ianmcburnie** [comment]
Ultimately, all components, but starting with those that make most sense, like Actionable.

Badge is also another good contender to start with as proof of concept.

ds4

```less
.badge {
    background-color: @ds4-color-core-red;
    color: @ds4-color-core-white;
}
```

ds

```less
.badge {
    background-color: @ds6-color-badge-background;
    color: @ds6-color-badge-text;
}
```
