### ISSUE TITLE
Icon: grouped selector redundancy in common icon css

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#509]
This is a follow on from the work done in https://github.com/eBay/skin/pull/471.

We currently have a lot of redundancy with our grouped icon selectors:

```less
span.icon--arrow-left,
svg.icon--arrow-left {
  height: 19px;
  width: 21px;
}
span.icon--arrow-right,
svg.icon--arrow-right {
  height: 19px;
  width: 21px;
}
span.icon--arrow-move,
svg.icon--arrow-move {
  height: 18px;
  width: 18px;
}
span.icon--arrow-right-bold,
svg.icon--arrow-right-bold {
  height: 21px;
  width: 24px;
}
span.icon--chevron-up,
svg.icon--chevron-up {
  height: 12px;
  width: 21px;
}
span.icon--chevron-down,
svg.icon--chevron-down {
  height: 12px;
  width: 21px;
}
span.icon--chevron-left,
svg.icon--chevron-left {
  height: 21px;
  width: 12px;
}
etc
```

This would be more optimal:

```less
.icon--arrow-left {
  height: 19px;
  width: 21px;
}
.icon--arrow-right {
  height: 19px;
  width: 21px;
}
.icon--arrow-move {
  height: 18px;
  width: 18px;
}
.icon--arrow-right-bold {
  height: 21px;
  width: 24px;
}
.icon--chevron-up {
  height: 12px;
  width: 21px;
}
.icon--chevron-down {
  height: 12px;
  width: 21px;
}
.icon--chevron-left {
  height: 21px;
  width: 12px;
}
```

The reason for the redundancy is because `svg.icon` is using the `.foreground-icon-base` mixin which sets a base width and height of 1rem. in order to override these base values, we have to match the specificity with a `svg` element selector for every icon, even though the width and height values are exactly the same for span or svg (!).

By removing the base width and height from the mixin, we can simplify the cascade and reduce these icon rules down to a single class selector. The base setting of 1rem by 1rem doesn't seem like a great idea anyhow, given that our icons are rarely exactly square - and so we could see aspect ratio issues (although I'm not sure if preserveAspectRatio could help in this regard).

Note that the `.background-icon-base` mixin does not provide a default width and height. So this change would make background and foreground base mixins consistent.
