### ISSUE TITLE
GH: module broken. Unable to resolve LESS variable.

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#565]
When importing `@ebay/skin/gh`, Lasso import is having trouble resolving the `@{dist-path}` variable in the source file.

Quick fix is just to hard code the path.

```less
@dist-path: "../../../../dist";

.actionable-mixin() {
    @import "@{dist-path}/actionable/ds6/actionable.css";
}

.badge-mixin() {
    @import "@{dist-path}/badge/ds6/badge.css";
}

.breadcrumb-mixin() {
    @import "@{dist-path}/breadcrumb/ds6/breadcrumb.css";
}

.button-mixin() {
    @import "@{dist-path}/button/ds6/button.css";
}

.checkbox-mixin() {
    @import "@{dist-path}/checkbox/ds6/checkbox.css";
}

.color-mixin() {
    @import "@{dist-path}/color/ds6/color.css";
}

.combobox-mixin() {
    @import "@{dist-path}/combobox/ds6/combobox.css";
}

.dialog-mixin() {
    @import "@{dist-path}/dialog/ds6/dialog.css";
}

.dropdown-mixin() {
    @import "@{dist-path}/dropdown/ds6/dropdown.css";
}

.field-mixin() {
    @import "@{dist-path}/field/ds6/field.css";
}

.global-mixin() {
    @import "@{dist-path}/global/ds6/global.css";
}

.icon-mixin() {
    @import "@{dist-path}/icon/background/ds6/background.css";
    @import "@{dist-path}/icon/foreground/ds6/foreground.css";
    @import "@{dist-path}/icon/common/ds6/common.css";
}

.label-mixin() {
    @import "@{dist-path}/label/ds6/label.css";
}

.link-mixin() {
    @import "@{dist-path}/link/ds6/link.css";
}

.notice-mixin() {
    @import "@{dist-path}/notice/ds6/notice.css";
}

.pagination-mixin() {
    @import "@{dist-path}/pagination/ds6/pagination.css";
}

.radio-mixin() {
    @import "@{dist-path}/radio/ds6/radio.css";
}

.select-mixin() {
    @import "@{dist-path}/select/ds6/select.css";
}

.switch-mixin() {
    @import "@{dist-path}/switch/ds6/switch.css";
}

.tab-mixin() {
    @import "@{dist-path}/tab/ds6/tab.css";
}

.textbox-mixin() {
    @import "@{dist-path}/textbox/ds6/textbox.css";
}

.tooltip-mixin() {
    @import "@{dist-path}/tooltip/ds6/tooltip.css";
}

.typography-mixin() {
    @import "@{dist-path}/typography/ds6/typography.css";
}

.utility-mixin() {
    @import "@{dist-path}/utility/ds6/utility.css";
}
```

![screen shot 2019-02-19 at 9 42 40 am](https://user-images.githubusercontent.com/38065/53035769-098d3d00-342b-11e9-8910-f1af5156b4cd.png)
